ChallengeInterval: 30 # in Seconds
AnnouncementsInterval: 10 # hoeveel seconden van te voren kondig je de challenge aan?

challenges:

  - name: kill_cow
    type: kill_entity
    entity: COW
    amount: 3

  - name: break_stone
    type: break_block
    block: STONE
    amount: 25

  - name: fill_water_bottle
    type: fill_item
    item: GLASS_BOTTLE
    amount: 1

  - name: craft_cake
    type: craft_item
    item: CAKE
    amount: 1

  - name: farm_wheat
    type: break_block
    block: WHEAT
    amount: 20

  - name: harvest_glow_berry
    type: farm_item
    block: CAVE_VINES_PLANT
    amount: 3