challengeIntervalSeconds: 30
announcementLeadTimeSeconds: 10
rewardCommand: "adjustbonusclaimblocks {player} {reward}"

games:
  - id: kill_cow
    type: kill_entity
    display_name: Kill 3 cows
    amount: 3
    reward: 5
    settings:
      entity: COW

  - id: break_stone
    type: break_block
    display_name: Break 25 stone
    amount: 25
    reward: 5
    settings:
      block: STONE

  - id: fill_water_bottle
    type: interaction
    display_name: Fill 1 water bottle
    amount: 1
    reward: 5
    settings:
      item: GLASS_BOTTLE

  - id: craft_cake
    type: craft_item
    display_name: Craft a cake
    amount: 1
    reward: 5
    settings:
      item: CAKE

  - id: farm_wheat
    type: farm_item
    display_name: Harvest 20 wheat
    amount: 20
    reward: 5
    settings:
      block: WHEAT

  - id: harvest_glow_berries
    type: farm_item
    display_name: Harvest 3 glow berries
    amount: 3
    reward: 5
    settings:
      block: CAVE_VINES_PLANT

  - id: type_the_word
    type: chat_word
    display_name: Type the word
    amount: 1
    reward: 5
    settings:
      ignore_case: true
      trim_input: true
      words:
        - diamant
        - creeper
        - nether
        - minecraft
