name: AnkieSMP_MinigamePlugin
description: $description
version: '${version}'

main: com.rensjam.AnkieSMP_MinigamePlugin.AnkieSMP_MinigamePlugin
api-version: '26.1.2'
load: POSTWORLD

authors: [ RensJAM ]
